---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kessel.project-kessel.org
  resources:
  - syncconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kessel.project-kessel.org
  resources:
  - syncconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - kessel.project-kessel.org
  resources:
  - syncconfigs/status
  verbs:
  - get
  - patch
  - update
