# This rule is not used by the project kube-kessel-sync itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to kessel.project-kessel.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-kessel-sync
    app.kubernetes.io/managed-by: kustomize
  name: syncconfig-viewer-role
rules:
- apiGroups:
  - kessel.project-kessel.org
  resources:
  - syncconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kessel.project-kessel.org
  resources:
  - syncconfigs/status
  verbs:
  - get
